# -*- coding: utf-8 -*-
"""Syntecxhub_Pandas_CSV_Reader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jQs-SuyzBm-O-2vqFJ3eFbfS0mpYKYjJ

Import Libraries and Load Data
"""

"""
Project 2: Pandas CSV Reader & Basic Analysis
Dataset: Olympic Athletes (athlete_events.csv)
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Set display options for better viewing
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_rows', 20)

print("=" * 60)
print("OLYMPIC ATHLETES DATASET ANALYSIS")
print("=" * 60)

# Load the CSV file
df = pd.read_csv('athlete_events.csv')
print(f"Dataset loaded successfully!")
print(f"Dataset shape: {df.shape}")
print(f"Number of rows: {df.shape[0]:,}")
print(f"Number of columns: {df.shape[1]}")

"""Initial Data Inspection"""

# ==================== INITIAL DATA INSPECTION ====================
print("\n" + "=" * 60)
print("PART 1: INITIAL DATA INSPECTION")
print("=" * 60)

# Display first 5 rows
print("\n--- First 5 rows (head) ---")
print(df.head())

# Display last 5 rows
print("\n--- Last 5 rows (tail) ---")
print(df.tail())

# Display random sample of 5 rows
print("\n--- Random sample of 5 rows ---")
print(df.sample(5))

# Display column names
print(f"\n--- Column Names ({len(df.columns)} columns) ---")
for i, col in enumerate(df.columns, 1):
    print(f"{i:2}. {col}")

"""Data Types and Basic Information"""

# ==================== DATA TYPES AND BASIC INFO ====================
print("\n" + "=" * 60)
print("PART 2: DATA TYPES AND BASIC INFORMATION")
print("=" * 60)

# Display data types
print("\n--- Data Types ---")
print(df.dtypes)

# Display concise info
print("\n--- DataFrame Info ---")
print(df.info())

# Display memory usage
print(f"\n--- Memory Usage ---")
print(f"Total memory: {df.memory_usage(deep=True).sum() / 1024**2:.2f} MB")

"""Summary Statistics for Numerical Columns"""

# ==================== SUMMARY STATISTICS ====================
print("\n" + "=" * 60)
print("PART 3: SUMMARY STATISTICS")
print("=" * 60)

# Basic statistics for numerical columns
print("\n--- Descriptive Statistics for Numerical Columns ---")
print(df.describe())

# Additional statistics for specific columns
print("\n--- Individual Statistics for Age ---")
print(f"Mean age: {df['Age'].mean():.2f}")
print(f"Median age: {df['Age'].median():.2f}")
print(f"Mode age: {df['Age'].mode()[0]}")
print(f"Min age: {df['Age'].min()}")
print(f"Max age: {df['Age'].max()}")
print(f"Standard deviation: {df['Age'].std():.2f}")
print(f"Variance: {df['Age'].var():.2f}")
print(f"Range: {df['Age'].max() - df['Age'].min()}")
print(f"25th percentile: {df['Age'].quantile(0.25):.2f}")
print(f"75th percentile: {df['Age'].quantile(0.75):.2f}")

# Statistics for Height
print("\n--- Statistics for Height ---")
print(f"Mean height: {df['Height'].mean():.2f} cm")
print(f"Median height: {df['Height'].median():.2f} cm")
print(f"Min height: {df['Height'].min():.2f} cm")
print(f"Max height: {df['Height'].max():.2f} cm")

# Statistics for Weight
print("\n--- Statistics for Weight ---")
print(f"Mean weight: {df['Weight'].mean():.2f} kg")
print(f"Median weight: {df['Weight'].median():.2f} kg")
print(f"Min weight: {df['Weight'].min():.2f} kg")
print(f"Max weight: {df['Weight'].max():.2f} kg")

"""Summary Statistics for Categorical Columns"""

# ==================== CATEGORICAL COLUMNS SUMMARY ====================
print("\n" + "=" * 60)
print("PART 4: CATEGORICAL COLUMNS SUMMARY")
print("=" * 60)

# Value counts for Sex
print("\n--- Sex Distribution ---")
print(df['Sex'].value_counts())
print(f"\nPercentage:")
print(df['Sex'].value_counts(normalize=True) * 100)

# Value counts for Season
print("\n--- Season Distribution ---")
print(df['Season'].value_counts())
print(f"\nPercentage:")
print(df['Season'].value_counts(normalize=True) * 100)

# Top 10 Teams
print("\n--- Top 10 Teams by Number of Athletes ---")
print(df['Team'].value_counts().head(10))

# Top 10 Sports
print("\n--- Top 10 Sports by Number of Events ---")
print(df['Sport'].value_counts().head(10))

# Medal Distribution
print("\n--- Medal Distribution ---")
print(df['Medal'].value_counts())
print(f"\nPercentage of medal winners:")
print(df['Medal'].notna().value_counts(normalize=True) * 100)

# Year distribution
print("\n--- Olympic Years Covered ---")
print(f"First Olympic year: {df['Year'].min()}")
print(f"Last Olympic year: {df['Year'].max()}")
print(f"Number of unique years: {df['Year'].nunique()}")
print(f"\nEvents per year:")
print(df['Year'].value_counts().sort_index().head(10))

"""Missing Values Analysis"""

# ==================== MISSING VALUES ANALYSIS ====================
print("\n" + "=" * 60)
print("PART 5: MISSING VALUES ANALYSIS")
print("=" * 60)

# Count missing values per column
print("\n--- Missing Values Count ---")
missing_count = df.isnull().sum()
print(missing_count)

# Percentage of missing values
print("\n--- Missing Values Percentage ---")
missing_percentage = (df.isnull().sum() / len(df)) * 100
for col, pct in missing_percentage.items():
    print(f"{col:10}: {pct:.2f}%")

# Visual representation of missing data
print("\n--- Columns with most missing values ---")
missing_df = pd.DataFrame({
    'Column': missing_percentage.index,
    'Missing_Percentage': missing_percentage.values
})
print(missing_df.sort_values('Missing_Percentage', ascending=False).head())

"""Filtering Rows"""

# ==================== FILTERING ROWS ====================
print("\n" + "=" * 60)
print("PART 6: FILTERING ROWS")
print("=" * 60)

# Filter by single condition: Summer Olympics
print("\n--- Summer Olympics only ---")
summer_df = df[df['Season'] == 'Summer']
print(f"Number of Summer Olympic records: {len(summer_df):,}")

# Filter by single condition: Female athletes
print("\n--- Female athletes only ---")
female_df = df[df['Sex'] == 'F']
print(f"Number of female athlete records: {len(female_df):,}")

# Multiple conditions: Female athletes in Summer Olympics
print("\n--- Female athletes in Summer Olympics ---")
female_summer = df[(df['Sex'] == 'F') & (df['Season'] == 'Summer')]
print(f"Number of records: {len(female_summer):,}")

# Filter by age: Athletes over 40
print("\n--- Athletes over 40 years old ---")
over_40 = df[df['Age'] > 40]
print(f"Number of records: {len(over_40):,}")
print(over_40[['Name', 'Age', 'Sport', 'Year']].head(10))

# Filter by medal winners
print("\n--- Medal winners only ---")
medal_winners = df[df['Medal'].notna()]
print(f"Number of medal-winning records: {len(medal_winners):,}")
print(medal_winners[['Name', 'Team', 'Sport', 'Medal']].head(10))

# Complex filter: Gold medalists from USA in Basketball
print("\n--- USA Basketball Gold Medalists ---")
usa_basketball_gold = df[(df['Team'] == 'United States') &
                          (df['Sport'] == 'Basketball') &
                          (df['Medal'] == 'Gold')]
print(f"Number of records: {len(usa_basketball_gold):,}")
print(usa_basketball_gold[['Name', 'Year', 'Event']].head(10))

# Filter by list of values
print("\n--- Athletes from specific countries (USA, CHN, RUS) ---")
selected_countries = df[df['Team'].isin(['United States', 'China', 'Russia'])]
print(f"Number of records: {len(selected_countries):,}")
print(selected_countries['Team'].value_counts())

# Filter by string condition (Name starting with 'A')
print("\n--- Athletes whose names start with 'A' ---")
a_names = df[df['Name'].str.startswith('A', na=False)]
print(f"Number of records: {len(a_names):,}")
print(a_names['Name'].head(10))

"""Selecting Columns"""

# ==================== SELECTING COLUMNS ====================
print("\n" + "=" * 60)
print("PART 7: SELECTING COLUMNS")
print("=" * 60)

# Select single column
print("\n--- Single column: Athlete Names (first 10) ---")
print(df['Name'].head(10))

# Select multiple columns
print("\n--- Multiple columns: ID, Name, Age, Sport ---")
basic_info = df[['ID', 'Name', 'Age', 'Sport']]
print(basic_info.head(10))

# Select columns by data type
print("\n--- Select only numerical columns ---")
numerical_cols = df.select_dtypes(include=['int64', 'float64'])
print(f"Numerical columns: {list(numerical_cols.columns)}")
print(numerical_cols.head())

# Select columns by data type (categorical/object)
print("\n--- Select only categorical columns ---")
categorical_cols = df.select_dtypes(include=['object'])
print(f"Categorical columns: {list(categorical_cols.columns)}")
print(categorical_cols.head())

# Select columns using loc (by name)
print("\n--- Select columns using loc (Name to Age) ---")
print(df.loc[:, 'Name':'Age'].head())

# Select columns using iloc (by position)
print("\n--- Select first 5 columns using iloc ---")
print(df.iloc[:, :5].head())

# Select specific rows and columns
print("\n--- Rows 10-15, columns 0-3 ---")
print(df.iloc[10:15, 0:4])

"""Slicing Subsets"""

# ==================== SLICING SUBSETS ====================
print("\n" + "=" * 60)
print("PART 8: SLICING SUBSETS")
print("=" * 60)

# Slice using loc (by index label)
print("\n--- Rows 5 to 10 with Name and Sport columns ---")
print(df.loc[5:10, ['Name', 'Sport']])

# Slice using iloc (by position)
print("\n--- First 10 rows, first 3 columns ---")
print(df.iloc[:10, :3])

# Slice with step
print("\n--- Every 1000th row (first 10) ---")
print(df.iloc[::1000, [1, 2, 8, 12]].head(10))

# Get specific rows by index list
print("\n--- Specific rows [100, 200, 300, 400, 500] ---")
print(df.iloc[[100, 200, 300, 400, 500], [1, 2, 8, 9]])

# Conditional selection with column selection
print("\n--- Gold medalists (Name, Sport, Year) ---")
gold_medalists = df[df['Medal'] == 'Gold'][['Name', 'Sport', 'Year', 'Team']]
print(gold_medalists.head(10))

# Chaining conditions with column selection
print("\n--- Female swimmers from USA ---")
usa_female_swimmers = df[(df['Sex'] == 'F') &
                         (df['Team'] == 'United States') &
                         (df['Sport'] == 'Swimming')][['Name', 'Year', 'Event']]
print(usa_female_swimmers.head(10))

"""GroupBy Operations"""

# ==================== GROUPBY OPERATIONS ====================
print("\n" + "=" * 60)
print("PART 9: GROUPBY OPERATIONS")
print("=" * 60)

# Group by Sex - average age
print("\n--- Average age by Sex ---")
print(df.groupby('Sex')['Age'].mean())

# Group by Season - statistics
print("\n--- Statistics by Season ---")
print(df.groupby('Season')['Age'].agg(['mean', 'min', 'max', 'count']))

# Group by Medal - count and average age
print("\n--- Medal statistics ---")
print(df.groupby('Medal')['Age'].agg(['count', 'mean']))

# Multiple groupby columns
print("\n--- Count by Season and Sex ---")
print(df.groupby(['Season', 'Sex']).size().unstack())

# Group by Sport - average height and weight
print("\n--- Top 10 Sports by average height ---")
sport_stats = df.groupby('Sport')[['Height', 'Weight']].mean().round(1)
print(sport_stats.sort_values('Height', ascending=False).head(10))

# Group by Year - athlete count over time
print("\n--- Athlete count by year (top 10) ---")
year_counts = df.groupby('Year').size().sort_index()
print(year_counts)

# Complex aggregation
print("\n--- Multiple aggregations by Sport ---")
sport_agg = df.groupby('Sport').agg({
    'Age': ['mean', 'min', 'max'],
    'Height': 'mean',
    'ID': 'count'
}).round(1)
print(sport_agg.head(10))

"""Medal Analysis"""

# ==================== MEDAL ANALYSIS ====================
print("\n" + "=" * 60)
print("PART 10: MEDAL ANALYSIS")
print("=" * 60)

# Medal count by country
print("\n--- Top 20 Countries by Total Medals ---")
medal_by_country = df[df['Medal'].notna()].groupby('Team')['Medal'].count().sort_values(ascending=False)
print(medal_by_country.head(20))

# Medal breakdown by country (Gold, Silver, Bronze)
print("\n--- Top 10 Countries by Medal Type ---")
medal_pivot = pd.crosstab(df[df['Medal'].notna()]['Team'],
                          df[df['Medal'].notna()]['Medal'])
medal_pivot['Total'] = medal_pivot.sum(axis=1)
print(medal_pivot.sort_values('Total', ascending=False).head(10))

# Medal count by sport
print("\n--- Top 10 Sports by Medal Count ---")
medal_by_sport = df[df['Medal'].notna()].groupby('Sport')['Medal'].count().sort_values(ascending=False)
print(medal_by_sport.head(10))

# Medalists by age group
print("\n--- Medalists by Age Group ---")
df['Age_Group'] = pd.cut(df['Age'], bins=[0, 20, 25, 30, 35, 40, 100],
                          labels=['<20', '20-25', '25-30', '30-35', '35-40', '40+'])
age_medal = df[df['Medal'].notna()].groupby('Age_Group')['Medal'].count()
print(age_medal)

# Multiple medal winners
print("\n--- Athletes with multiple medals (top 10) ---")
multi_medal = df[df['Medal'].notna()].groupby('Name')['Medal'].count().sort_values(ascending=False)
print(multi_medal.head(10))

"""Time Series Analysis"""

# ==================== TIME SERIES ANALYSIS ====================
print("\n" + "=" * 60)
print("PART 11: TIME SERIES ANALYSIS")
print("=" * 60)

# Athlete count over years
print("\n--- Athlete count by year ---")
yearly_athletes = df.groupby('Year').size()
print(yearly_athletes)

# Female participation over time
print("\n--- Female participation percentage over time ---")
female_pct = df.groupby('Year').apply(
    lambda x: (x['Sex'] == 'F').mean() * 100
).round(2)
print(female_pct)

# Medal counts by year
print("\n--- Medal counts by year (top 10 years) ---")
medals_by_year = df[df['Medal'].notna()].groupby('Year').size().sort_values(ascending=False)
print(medals_by_year.head(10))

# Summer vs Winter over time
print("\n--- Summer vs Winter athlete counts ---")
season_year = df.groupby(['Year', 'Season']).size().unstack()
print(season_year.tail(10))

# Average age over time
print("\n--- Average athlete age by year ---")
avg_age_by_year = df.groupby('Year')['Age'].mean().round(1)
print(avg_age_by_year.tail(10))

"""Athletic Performance Analysis"""

# ==================== ATHLETIC PERFORMANCE ANALYSIS ====================
print("\n" + "=" * 60)
print("PART 12: ATHLETIC PERFORMANCE ANALYSIS")
print("=" * 60)

# Average height by sport
print("\n--- Top 10 Sports by Average Height ---")
sport_height = df.groupby('Sport')['Height'].mean().sort_values(ascending=False).round(1)
print(sport_height.head(10))

# Average weight by sport
print("\n--- Top 10 Sports by Average Weight ---")
sport_weight = df.groupby('Sport')['Weight'].mean().sort_values(ascending=False).round(1)
print(sport_weight.head(10))

# Height and weight by medal status
print("\n--- Height and Weight by Medal Status ---")
medal_stats = df.groupby(df['Medal'].notna()).agg({
    'Height': 'mean',
    'Weight': 'mean'
}).round(1)
medal_stats.index = ['No Medal', 'Medal Winner']
print(medal_stats)

# Sport-specific analysis (Basketball)
print("\n--- Basketball Players Statistics ---")
basketball = df[df['Sport'] == 'Basketball']
print(f"Average height: {basketball['Height'].mean():.1f} cm")
print(f"Average weight: {basketball['Weight'].mean():.1f} kg")
print(f"Average age: {basketball['Age'].mean():.1f} years")

# Gender differences by sport
print("\n--- Height difference by gender in Basketball ---")
bb_gender = basketball.groupby('Sex')['Height'].mean().round(1)
print(bb_gender)

# BMI calculation
print("\n--- BMI by Sport (top 10) ---")
df_bmi = df.copy()
df_bmi['BMI'] = df_bmi['Weight'] / ((df_bmi['Height']/100) ** 2)
bmi_by_sport = df_bmi.groupby('Sport')['BMI'].mean().round(2).sort_values(ascending=False)
print(bmi_by_sport.head(10))

"""Country Analysis"""

# ==================== COUNTRY ANALYSIS ====================
print("\n" + "=" * 60)
print("PART 13: COUNTRY ANALYSIS")
print("=" * 60)

# Top countries by athlete count
print("\n--- Top 20 Countries by Athlete Count ---")
country_athletes = df.groupby('Team')['ID'].nunique().sort_values(ascending=False)
print(country_athletes.head(20))

# Countries by average height
print("\n--- Top 10 Countries by Average Height ---")
country_height = df.groupby('Team')['Height'].mean().sort_values(ascending=False).round(1)
print(country_height.head(10))

# Countries with most sports participation
print("\n--- Top 10 Countries by Sports Diversity ---")
country_sports = df.groupby('Team')['Sport'].nunique().sort_values(ascending=False)
print(country_sports.head(10))

# NOC code analysis
print("\n--- Top 10 NOC codes by athlete count ---")
noc_counts = df.groupby('NOC')['ID'].nunique().sort_values(ascending=False)
print(noc_counts.head(10))

# Country performance in specific sport (Swimming)
print("\n--- Top Countries in Swimming (medal count) ---")
swimming_medals = df[(df['Sport'] == 'Swimming') & (df['Medal'].notna())]
swim_country = swimming_medals.groupby('Team')['Medal'].count().sort_values(ascending=False)
print(swim_country.head(10))

"""Athlete Age Analysis"""

# ==================== ATHLETE AGE ANALYSIS ====================
print("\n" + "=" * 60)
print("PART 14: ATHLETE AGE ANALYSIS")
print("=" * 60)

# Age distribution
print("\n--- Age Distribution Summary ---")
print(f"Youngest athlete: {df['Age'].min()} years old")
print(f"Oldest athlete: {df['Age'].max()} years old")
print(f"Average age: {df['Age'].mean():.1f} years")
print(f"Median age: {df['Age'].median():.1f} years")

# Age groups
print("\n--- Athletes by Age Group ---")
age_bins = [0, 18, 25, 30, 35, 40, 50, 100]
age_labels = ['<18', '18-25', '25-30', '30-35', '35-40', '40-50', '50+']
df['Age_Group'] = pd.cut(df['Age'], bins=age_bins, labels=age_labels)
age_group_counts = df['Age_Group'].value_counts().sort_index()
print(age_group_counts)

# Age by sport (youngest)
print("\n--- Top 10 Sports with Youngest Athletes (avg age) ---")
youngest_sports = df.groupby('Sport')['Age'].mean().sort_values()
print(youngest_sports.head(10))

# Age by sport (oldest)
print("\n--- Top 10 Sports with Oldest Athletes (avg age) ---")
oldest_sports = df.groupby('Sport')['Age'].mean().sort_values(ascending=False)
print(oldest_sports.head(10))

# Age trends over time
print("\n--- Age trends over decades ---")
df['Decade'] = (df['Year'] // 10) * 10
decade_age = df.groupby('Decade')['Age'].mean().round(1)
print(decade_age)

"""Filtered Results and Save to CSV"""

# ==================== FILTERED RESULTS AND SAVE TO CSV ====================
print("\n" + "=" * 60)
print("PART 15: FILTERED RESULTS AND SAVE TO CSV")
print("=" * 60)

# Create filtered dataset: Medal winners from 2000 onwards
print("\n--- Creating filtered dataset: Medal winners from 2000 onwards ---")
recent_medalists = df[(df['Year'] >= 2000) & (df['Medal'].notna())]
print(f"Records found: {len(recent_medalists):,}")
print(recent_medalists[['Name', 'Team', 'Sport', 'Year', 'Medal']].head(10))

# Save to CSV
recent_medalists.to_csv('recent_medalists.csv', index=False)
print("Saved to 'recent_medalists.csv'")

# Create filtered dataset: USA athletes
print("\n--- Creating filtered dataset: USA athletes ---")
usa_athletes = df[df['Team'] == 'United States']
print(f"Records found: {len(usa_athletes):,}")
print(usa_athletes[['Name', 'Sport', 'Year', 'Medal']].head(10))

# Save to Excel
usa_athletes.to_excel('usa_athletes.xlsx', index=False)
print("Saved to 'usa_athletes.xlsx'")

# Create summary dataset
print("\n--- Creating summary dataset: Medal counts by country and year ---")
medal_summary = df[df['Medal'].notna()].groupby(['Year', 'Team', 'Medal']).size().reset_index(name='Count')
print(medal_summary.head(10))

# Save summary
medal_summary.to_csv('medal_summary.csv', index=False)
print("Saved to 'medal_summary.csv'")

"""Advanced Analysis - Pivot Tables"""

# ==================== ADVANCED ANALYSIS - PIVOT TABLES ====================
print("\n" + "=" * 60)
print("PART 16: PIVOT TABLES")
print("=" * 60)

# Pivot table: Medal counts by Year and Medal Type
print("\n--- Medal counts by Year and Medal Type (first 10 years) ---")
medal_pivot_year = pd.pivot_table(
    df[df['Medal'].notna()],
    values='ID',
    index='Year',
    columns='Medal',
    aggfunc='count',
    fill_value=0
)
print(medal_pivot_year.head(10))

# Pivot table: Average age by Sport and Sex
print("\n--- Average age by Sport and Sex (top 10 sports) ---")
age_pivot = pd.pivot_table(
    df,
    values='Age',
    index='Sport',
    columns='Sex',
    aggfunc='mean',
    fill_value=0
).round(1)
print(age_pivot.head(10))

# Pivot table: Count of athletes by Season and Sex
print("\n--- Athlete count by Season and Sex ---")
season_sex_pivot = pd.pivot_table(
    df,
    values='ID',
    index='Season',
    columns='Sex',
    aggfunc='count',
    fill_value=0
)
print(season_sex_pivot)

# Multi-index pivot: Average height by Sport and Medal status
print("\n--- Average height by Sport and Medal status (first 10 sports) ---")
height_pivot = pd.pivot_table(
    df,
    values='Height',
    index='Sport',
    columns=df['Medal'].notna().map({True: 'Medalist', False: 'Non-medalist'}),
    aggfunc='mean',
    fill_value=0
).round(1)
print(height_pivot.head(10))

"""Correlation Analysis"""

# ==================== CORRELATION ANALYSIS ====================
print("\n" + "=" * 60)
print("PART 17: CORRELATION ANALYSIS")
print("=" * 60)

# Select numerical columns for correlation
numerical_cols = ['Age', 'Height', 'Weight', 'Year']
corr_df = df[numerical_cols].dropna()

# Calculate correlation matrix
print("\n--- Correlation Matrix ---")
correlation = corr_df.corr()
print(correlation)

# Pairwise correlations
print("\n--- Key Correlations ---")
print(f"Height vs Weight correlation: {correlation.loc['Height', 'Weight']:.3f}")
print(f"Age vs Height correlation: {correlation.loc['Age', 'Height']:.3f}")
print(f"Age vs Weight correlation: {correlation.loc['Age', 'Weight']:.3f}")
print(f"Year vs Height correlation: {correlation.loc['Year', 'Height']:.3f}")

# Group correlation by sport (example: Basketball)
print("\n--- Basketball: Height-Weight correlation ---")
basketball_corr = df[df['Sport'] == 'Basketball'][['Height', 'Weight']].dropna().corr()
print(f"Basketball Height-Weight correlation: {basketball_corr.loc['Height', 'Weight']:.3f}")

# Group correlation by sport (example: Gymnastics)
print("\n--- Gymnastics: Height-Weight correlation ---")
gymnastics_corr = df[df['Sport'] == 'Gymnastics'][['Height', 'Weight']].dropna().corr()
print(f"Gymnastics Height-Weight correlation: {gymnastics_corr.loc['Height', 'Weight']:.3f}")

"""Most Successful Athletes"""

# ==================== MOST SUCCESSFUL ATHLETES ====================
print("\n" + "=" * 60)
print("PART 18: MOST SUCCESSFUL ATHLETES")
print("=" * 60)

# Athletes with most total medals
print("\n--- Top 20 Athletes by Total Medals ---")
top_athletes = df[df['Medal'].notna()].groupby('Name').agg({
    'Medal': 'count',
    'Sport': 'first',
    'Team': 'first'
}).rename(columns={'Medal': 'Total_Medals'}).sort_values('Total_Medals', ascending=False)
print(top_athletes.head(20))

# Athletes with most Gold medals
print("\n--- Top 20 Athletes by Gold Medals ---")
gold_athletes = df[df['Medal'] == 'Gold'].groupby('Name').agg({
    'Medal': 'count',
    'Sport': 'first',
    'Team': 'first'
}).rename(columns={'Medal': 'Gold_Medals'}).sort_values('Gold_Medals', ascending=False)
print(gold_athletes.head(20))

# Athletes who competed in most Olympics
print("\n--- Athletes who competed in most Olympics ---")
olympic_count = df.groupby('Name')['Year'].nunique().sort_values(ascending=False)
print(olympic_count.head(20))

# Athletes who competed in multiple sports
print("\n--- Athletes who competed in multiple sports ---")
multi_sport = df.groupby('Name')['Sport'].nunique()
multi_sport = multi_sport[multi_sport > 1].sort_values(ascending=False)
print(multi_sport.head(20))

# Youngest medalists
print("\n--- Youngest Gold Medalists ---")
youngest_gold = df[df['Medal'] == 'Gold'].sort_values('Age').head(10)
print(youngest_gold[['Name', 'Age', 'Sport', 'Year', 'Team']])

# Oldest medalists
print("\n--- Oldest Gold Medalists ---")
oldest_gold = df[df['Medal'] == 'Gold'].sort_values('Age', ascending=False).head(10)
print(oldest_gold[['Name', 'Age', 'Sport', 'Year', 'Team']])

"""Final Summary and Insights"""

# ==================== FINAL SUMMARY AND INSIGHTS ====================
print("\n" + "=" * 60)
print("PART 19: FINAL SUMMARY AND INSIGHTS")
print("=" * 60)

# Create a summary DataFrame
summary = pd.DataFrame({
    'Metric': [
        'Total Records',
        'Total Athletes',
        'Total Olympic Games',
        'Years Covered',
        'Number of Sports',
        'Number of Countries',
        'Total Medals Awarded',
        'Gold Medals',
        'Silver Medals',
        'Bronze Medals',
        'Male Athletes (%)',
        'Female Athletes (%)',
        'Summer Olympics Records',
        'Winter Olympics Records',
        'Average Age',
        'Average Height (cm)',
        'Average Weight (kg)',
        'Oldest Athlete Age',
        'Youngest Athlete Age'
    ],
    'Value': [
        f"{len(df):,}",
        f"{df['ID'].nunique():,}",
        f"{df['Year'].nunique()}",
        f"{df['Year'].min()} - {df['Year'].max()}",
        f"{df['Sport'].nunique()}",
        f"{df['Team'].nunique()}",
        f"{df['Medal'].notna().sum():,}",
        f"{(df['Medal'] == 'Gold').sum():,}",
        f"{(df['Medal'] == 'Silver').sum():,}",
        f"{(df['Medal'] == 'Bronze').sum():,}",
        f"{(df['Sex'] == 'M').mean() * 100:.1f}%",
        f"{(df['Sex'] == 'F').mean() * 100:.1f}%",
        f"{len(df[df['Season'] == 'Summer']):,}",
        f"{len(df[df['Season'] == 'Winter']):,}",
        f"{df['Age'].mean():.1f} years",
        f"{df['Height'].mean():.1f} cm",
        f"{df['Weight'].mean():.1f} kg",
        f"{df['Age'].max():.0f}",
        f"{df['Age'].min():.0f}"
    ]
})

print(summary.to_string(index=False))

# Key Insights
print("\n" + "=" * 60)
print("KEY INSIGHTS")
print("=" * 60)

print("""
1. Participation Trends:
   - The dataset contains records from {} to {} Olympics
   - Female participation has increased significantly over time
   - Summer Olympics have {} records vs {} for Winter

2. Medal Distribution:
   - Total medals awarded: {:,}
   - Most medals won by: {} athletes
   - Most successful country: {} with {} medals

3. Athlete Demographics:
   - Average athlete age: {:.1f} years
   - Average height: {:.1f} cm
   - Average weight: {:.1f} kg
   - Male to female ratio: {:.1f}% / {:.1f}%

4. Sports Diversity:
   - Total sports represented: {}
   - Most popular sport: {} with {} athletes

5. Interesting Facts:
   - Youngest medalist: {} years old
   - Oldest medalist: {} years old
   - Athletes who competed in multiple Olympics: {}
   - Athletes who won medals in multiple sports: {}
""".format(
    df['Year'].min(), df['Year'].max(),
    len(df[df['Season'] == 'Summer']), len(df[df['Season'] == 'Winter']),
    df['Medal'].notna().sum(),
    df[df['Medal'].notna()].groupby('Name').size().idxmax(),
    df[df['Medal'].notna()].groupby('Team').size().idxmax(),
    df[df['Medal'].notna()].groupby('Team').size().max(),
    df['Age'].mean(), df['Height'].mean(), df['Weight'].mean(),
    (df['Sex'] == 'M').mean() * 100, (df['Sex'] == 'F').mean() * 100,
    df['Sport'].nunique(),
    df.groupby('Sport').size().idxmax(),
    df.groupby('Sport').size().max(),
    df[df['Medal'].notna()]['Age'].min(),
    df[df['Medal'].notna()]['Age'].max(),
    df.groupby('Name')['Year'].nunique().gt(1).sum(),
    df.groupby('Name')['Sport'].nunique().gt(1).sum()
))

print("\n Project 2: Pandas CSV Reader & Basic Analysis completed successfully!")

